// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5qKB8Tp-7cD-iYOhJG5Tp0XL8YevsZEA',
    appId: '1:897897607852:web:1ac31da57244027e70e509',
    messagingSenderId: '897897607852',
    projectId: 'taskorbit-979dc',
    authDomain: 'taskorbit-979dc.firebaseapp.com',
    storageBucket: 'taskorbit-979dc.firebasestorage.app',
    measurementId: 'G-WEY9D65Y2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-N8hqLgYFDfFRY82YY_gPB2gtCisAjpk',
    appId: '1:897897607852:android:7f988afb0a07466d70e509',
    messagingSenderId: '897897607852',
    projectId: 'taskorbit-979dc',
    storageBucket: 'taskorbit-979dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF3evxl6AOhCE8Af38y3tV_WXw0Y70CEQ',
    appId: '1:897897607852:ios:3c2dc3466e38ff2270e509',
    messagingSenderId: '897897607852',
    projectId: 'taskorbit-979dc',
    storageBucket: 'taskorbit-979dc.firebasestorage.app',
    iosBundleId: 'com.example.taskOrbit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF3evxl6AOhCE8Af38y3tV_WXw0Y70CEQ',
    appId: '1:897897607852:ios:3c2dc3466e38ff2270e509',
    messagingSenderId: '897897607852',
    projectId: 'taskorbit-979dc',
    storageBucket: 'taskorbit-979dc.firebasestorage.app',
    iosBundleId: 'com.example.taskOrbit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5qKB8Tp-7cD-iYOhJG5Tp0XL8YevsZEA',
    appId: '1:897897607852:web:1c31af651261f96e70e509',
    messagingSenderId: '897897607852',
    projectId: 'taskorbit-979dc',
    authDomain: 'taskorbit-979dc.firebaseapp.com',
    storageBucket: 'taskorbit-979dc.firebasestorage.app',
    measurementId: 'G-00FX406QLT',
  );
}
