// Mocks generated by Mockito 5.4.6 from annotations
// in task_orbit/test/features/authentication/domain/usecases/user_sign_up_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:task_orbit/core/error/failure.dart' as _i5;
import 'package:task_orbit/features/authentication/domain/entities/user.dart'
    as _i6;
import 'package:task_orbit/features/authentication/domain/repository/auth_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRepository extends _i1.Mock implements _i2.IAuthRepository {
  MockIAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.User>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.User>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i6.User>>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.User>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.User>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.User>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i6.User>>(
                this,
                Invocation.method(#getCurrentUser, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.User>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.User>> signUp({
    required String? name,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #name: name,
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.User>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i6.User>>(
                this,
                Invocation.method(#signUp, [], {
                  #name: name,
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.User>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> forgotPassword({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [], {#email: email}),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#forgotPassword, [], {#email: email}),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> changePassword({
    required String? oldPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #oldPassword: oldPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#changePassword, [], {
                  #oldPassword: oldPassword,
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#sendEmailVerification, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.User>> checkEmailVerified({
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmailVerified, [], {#name: name}),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.User>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i6.User>>(
                this,
                Invocation.method(#checkEmailVerified, [], {#name: name}),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.User>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> deleteCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#deleteCurrentUser, []),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#deleteCurrentUser, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}
